apiVersion: v1
kind: Secret
metadata:
  name: ssh-openvpn-tunnel-secret
type: Opaque
stringData:
  VPN_CONFIG_B64: "<base64-of-your-ovpn-file>"
  VPN_USERNAME: "<vpn-username>"
  VPN_PASSWORD: "<vpn-password>"
  SSH_KEY_B64: "<base64-of-your-private-key>"
  SSH_HOST: "<ssh-host>"
  SSH_USER: "<ssh-user>"
  REMOTE_PORT: "2222"
  TARGET_HOST: "192.168.64.6"
  TARGET_PORT: "22"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh-openvpn-tunnel
  labels:
    app: ssh-openvpn-tunnel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssh-openvpn-tunnel
  template:
    metadata:
      labels:
        app: ssh-openvpn-tunnel
    spec:
      containers:
        - name: tunnel
          image: ghcr.io/pradeep-av/ssh-openvpn-tunnel:main
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: ssh-openvpn-tunnel-secret
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - name: dev-net-tun
              mountPath: /dev/net/tun
      volumes:
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
